- hosts: all
  user: ubuntu
  sudo: false
  tasks:

  - name: create gigapower
    file: path={{ ansible_env.HOME }}/gigapower state=directory mode=0755

  - name: download gigapower jar
    get_url:
      url=https://github.com/mtdoyle/ATTGigapowerFinder/blob/0.1/out/artifacts/ATTGigapowerFinder_jar/ATTGigapowerFinder.jar
      dest={{ ansible_env.HOME }}/gigapower/ATTGigapowerFinder.jar
      force=yes

  - name: download gigapower property file
    get_url:
      url=https://raw.githubusercontent.com/mtdoyle/ATTGigapowerFinder/0.1/resources/properties/local.properties
      dest={{ ansible_env.HOME }}/gigapower

  - name: replace ip in property file
    replace: dest={{ ansible_env.HOME }}/gigapower/local.properties regexp='^databaseServer=.*' replace='databaseServer={{ ansible_eth0[\'ipv4\'][\'address\'] }}'

  - name: replace ip in property file
    replace: dest={{ ansible_env.HOME }}/gigapower/local.properties regexp='^rabbitmqServer=.*' replace='rabbitmqServer={{ ansible_eth0[\'ipv4\'][\'address\'] }}'

  - name: get load_rabbitmq.py
    get_url:
      url=https://raw.githubusercontent.com/mtdoyle/ATTGigapowerFinder/0.1/resources/LoadRabbitMQ/load_rabbitmq.py
      dest={{ ansible_env.HOME }}/gigapower/
  
  - name: install pika dependency for load_rabbitmq.py
    pip: name=pika
    become: yes
    become_method: sudo

  - name: get load_rabbitmq.py
    get_url:
      url=https://github.com/mtdoyle/ATTGigapowerFinder/raw/master/Resources/LoadRabbitMQ/addresses
      dest={{ ansible_env.HOME }}/gigapower/addresses
